const champList=[{
    key: '0000',
    name: 'Aatrox',
    image: require('../assets/campeoes/aatrox.png'),
    bordao: 'a Espada Darkin', 
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0001',
    name: 'Ahri',
    image: require('../assets/campeoes/ahri.png'),
    bordao: 'a Raposa de Nove Caudas',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0002',
    name: 'Akali',
    image: require('../assets/campeoes/akali.png'),
    bordao: 'o Punho das Sombras',
    rotas: 'Top e Mid',
    dano: 'Híbrido',
    funcao: 'Assassino',
},
{
    key: '0003',
    name: 'Askhan',
    image: require('../assets/campeoes/askhan.jpg'),
    bordao: 'o Sentinela Rebelde',
    rotas: 'Top Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
},
{
    key: '0004',
    name: 'Alistar',
    image: require('../assets/campeoes/alistar.jpg'),
    bordao: 'o Minotauro',
    rotas: 'Bot',
    dano: 'Dano Mágico',
    funcao: 'Tank',
},
{
    key: '0005',
    name: 'Amumu',
    image: require('../assets/campeoes/amumu.jpg'),
    bordao: 'a Múmia Triste',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Tank',
},
{
    key: '0006',
    name: 'Anivia',
    image: require('../assets/campeoes/anivia.jpg'),
    bordao: 'a Criofênix',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0007',
    name: 'Annie',
    image: require('../assets/campeoes/annie.jpg'),
    bordao: 'a Criança Sombria',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0008',
    name: 'Aphelios',
    image: require('../assets/campeoes/aphelios.jpg'),
    bordao: 'a Arma dos Devotos',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
},
{
    key: '0009',
    name: 'Ashe',
    image: require('../assets/campeoes/ashe.jpg'),
    bordao: 'a Arqueira do Gelo',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
},
{
    key: '0010',
    name: 'Aurelion Sol',
    image: require('../assets/campeoes/aurelion.jpg'),
    bordao: 'O Forjador de Estrelas',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0011',
    name: 'Azir',
    image: require('../assets/campeoes/azir.jpg'),
    bordao: 'o Imperador das Areias',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0012',
    name: 'Bardo',
    image: require('../assets/campeoes/bardo.jpg'),
    bordao: 'o Protetor Andarilho',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
},
{
    key: '0013',
    name: "Bel'Veth",
    image: require('../assets/campeoes/belveth.jpg'),
    bordao: 'a Imperatriz do Vazio',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0014',
    name: 'Blitzcrank',
    image: require('../assets/campeoes/blitzcrank.jpg'),
    bordao: 'o Grande Golem a Vapor',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Tank',
},
{
    key: '0015',
    name: 'Brand',
    image: require('../assets/campeoes/brand.jpg'),
    bordao: 'a Vingança Flamejante',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
},
{
    key: '0016',
    name: 'Braum',
    image: require('../assets/campeoes/braum.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0017',
    name: 'Caitlyn',
    image: require('../assets/campeoes/caitlyn.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0018',
    name: 'Camille',
    image: require('../assets/campeoes/camille.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0019',
    name: 'Cassiopeia',
    image: require('../assets/campeoes/cassiopeia.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0020',
    name: 'Cho Gath',
    image: require('../assets/campeoes/chogath.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0021',
    name: 'Corki',
    image: require('../assets/campeoes/corki.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0022',
    name: 'Darius',
    image: require('../assets/campeoes/darius.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0023',
    name: 'Diana',
    image: require('../assets/campeoes/diana.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0024',
    name: 'Dr.Mundo',
    image: require('../assets/campeoes/drmundo.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0025',
    name: 'Draven',
    image: require('../assets/campeoes/draven.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0026',
    name: 'Ekko',
    image: require('../assets/campeoes/ekko.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0027',
    name: 'Elise',
    image: require('../assets/campeoes/elise.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0028',
    name: 'Evelynn',
    image: require('../assets/campeoes/evelynn.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0029',
    name: 'Ezreal',
    image: require('../assets/campeoes/ezreal.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0030',
    name: 'Fiddlesticks',
    image: require('../assets/campeoes/fiddle.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0031',
    name: 'Fiora',
    image: require('../assets/campeoes/fiora.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0032',
    name: 'Fizz',
    image: require('../assets/campeoes/fizz.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0033',
    name: 'Galio',
    image: require('../assets/campeoes/galio.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0034',
    name: 'GangPlank',
    image: require('../assets/campeoes/gangplank.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0035',
    name: 'Garen',
    image: require('../assets/campeoes/garen.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0036',
    name: 'Gnar',
    image: require('../assets/campeoes/gnar.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0037',
    name: 'Gragas',
    image: require('../assets/campeoes/gragas.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0038',
    name: 'Graves',
    image: require('../assets/campeoes/graves.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0039',
    name: 'Gwen',
    image: require('../assets/campeoes/gwen.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0040',
    name: 'Hecarim',
    image: require('../assets/campeoes/hecarim.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0041',
    name: 'Heimerdinger',
    image: require('../assets/campeoes/heimerdinger.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0042',
    name: 'Illaoi',
    image: require('../assets/campeoes/illaoi.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0043',
    name: 'Irelia',
    image: require('../assets/campeoes/irelia.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0044',
    name: 'Ivern',
    image: require('../assets/campeoes/ivern.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0045',
    name: 'Janna',
    image: require('../assets/campeoes/janna.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0046',
    name: 'Jarvan IV',
    image: require('../assets/campeoes/jarvan.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0047',
    name: 'Jax',
    image: require('../assets/campeoes/jax.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0048',
    name: 'Jayce',
    image: require('../assets/campeoes/jayce.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0049',
    name: 'Jhin',
    image: require('../assets/campeoes/jhin.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0050',
    name: 'Jinx',
    image: require('../assets/campeoes/jinx.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0051',
    name: "Kai'sa",
    image: require('../assets/campeoes/kaisa.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0052',
    name: 'Kalista',
    image: require('../assets/campeoes/kalista.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0053',
    name: 'Karma',
    image: require('../assets/campeoes/karma.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0054',
    name: 'Karthus',
    image: require('../assets/campeoes/karthus.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0055',
    name: 'Kassadin',
    image: require('../assets/campeoes/kassadin.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0056',
    name: 'Katarina',
    image: require('../assets/campeoes/katarina.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0057',
    name: 'Kayle',
    image: require('../assets/campeoes/kayle.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0058',
    name: 'Kayn',
    image: require('../assets/campeoes/kayn.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0059',
    name: 'Kennen',
    image: require('../assets/campeoes/kennen.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0060',
    name: "Kha'Zix",
    image: require('../assets/campeoes/khazix.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0061',
    name: 'Kindred',
    image: require('../assets/campeoes/kindred.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0062',
    name: 'Kled',
    image: require('../assets/campeoes/kled.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0063',
    name: "Kog'Maw",
    image: require('../assets/campeoes/kogmaw.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0064',
    name: 'Leblanc',
    image: require('../assets/campeoes/leblanc.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0065',
    name: 'Lee Sin',
    image: require('../assets/campeoes/leesin.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0066',
    name: 'Leona',
    image: require('../assets/campeoes/leona.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0067',
    name: 'Lilia',
    image: require('../assets/campeoes/lilia.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0068',
    name: 'Lissandra',
    image: require('../assets/campeoes/lissandra.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0069',
    name: 'Lucian',
    image: require('../assets/campeoes/lucian.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0070',
    name: 'Lulu',
    image: require('../assets/campeoes/lulu.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0071',
    name: 'Lux',
    image: require('../assets/campeoes/lux.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0072',
    name: 'Malphite',
    image: require('../assets/campeoes/malphite.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0073',
    name: 'Malzahar',
    image: require('../assets/campeoes/malzahar.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0074',
    name: 'Maokai',
    image: require('../assets/campeoes/maokai.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0075',
    name: 'Master Yi',
    image: require('../assets/campeoes/masteryi.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0076',
    name: 'Miss Fortune',
    image: require('../assets/campeoes/missfortune.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0077',
    name: 'Mordekaizer',
    image: require('../assets/campeoes/mordekaizer.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0078',
    name: 'Morgana',
    image: require('../assets/campeoes/morgana.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0079',
    name: 'Nami',
    image: require('../assets/campeoes/nami.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0080',
    name: 'Nasus',
    image: require('../assets/campeoes/nasus.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0081',
    name: 'Nautilus',
    image: require('../assets/campeoes/nautilus.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0082',
    name: 'Neeko',
    image: require('../assets/campeoes/neeko.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0083',
    name: 'Nidalee',
    image: require('../assets/campeoes/nidalee.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0084',
    name: 'Nocturne',
    image: require('../assets/campeoes/nocturne.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0085',
    name: 'Nunu e Willump',
    image: require('../assets/campeoes/nunu.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0086',
    name: 'Olaf',
    image: require('../assets/campeoes/olaf.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0087',
    name: 'Orianna',
    image: require('../assets/campeoes/orianna.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0088',
    name: 'Ornn',
    image: require('../assets/campeoes/ornn.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0089',
    name: 'Pantheon',
    image: require('../assets/campeoes/pantheon.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0090',
    name: 'Poppy',
    image: require('../assets/campeoes/poppy.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0091',
    name: 'Pyke',
    image: require('../assets/campeoes/pyke.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0092',
    name: 'Qiyana',
    image: require('../assets/campeoes/qiyana.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0093',
    name: 'Quinn',
    image: require('../assets/campeoes/quinn.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0094',
    name: 'Rakan',
    image: require('../assets/campeoes/rakan.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0095',
    name: 'Rammus',
    image: require('../assets/campeoes/rammus.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0096',
    name: "Rek'Sai",
    image: require('../assets/campeoes/reksai.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0097',
    name: 'Rell',
    image: require('../assets/campeoes/rell.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0098',
    name: 'Renata Glasc',
    image: require('../assets/campeoes/renata.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0099',
    name: 'Renekton',
    image: require('../assets/campeoes/renekton.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '00100',
    name: 'Rengar',
    image: require('../assets/campeoes/rengar.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0101',
    name: 'Riven',
    image: require('../assets/campeoes/riven.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0102',
    name: 'Rumble',
    image: require('../assets/campeoes/rumble.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0103',
    name: 'Ryze',
    image: require('../assets/campeoes/ryze.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0104',
    name: 'Samira',
    image: require('../assets/campeoes/samira.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0105',
    name: 'Sejuani',
    image: require('../assets/campeoes/sejuani.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0106',
    name: 'Senna',
    image: require('../assets/campeoes/senna.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0107',
    name: 'Seraphine',
    image: require('../assets/campeoes/seraphine.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0108',
    name: 'Sett',
    image: require('../assets/campeoes/sett.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0109',
    name: 'Shaco',
    image: require('../assets/campeoes/shaco.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0110',
    name: 'Shen',
    image: require('../assets/campeoes/shen.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0111',
    name: 'Shyvana',
    image: require('../assets/campeoes/shyvana.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0112',
    name: 'Singed',
    image: require('../assets/campeoes/singed.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0113',
    name: 'Sion',
    image: require('../assets/campeoes/sion.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0114',
    name: 'Sivir',
    image: require('../assets/campeoes/sivir.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0115',
    name: 'Skarner',
    image: require('../assets/campeoes/skarner.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0116',
    name: 'Sona',
    image: require('../assets/campeoes/sona.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0117',
    name: 'Soraka',
    image: require('../assets/campeoes/soraka.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0118',
    name: 'Swain',
    image: require('../assets/campeoes/swain.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0119',
    name: 'Sylas',
    image: require('../assets/campeoes/sylas.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0120',
    name: 'Syndra',
    image: require('../assets/campeoes/syndra.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0121',
    name: 'Tahm Kench',
    image: require('../assets/campeoes/tk.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0122',
    name: 'Taliyah',
    image: require('../assets/campeoes/taliyah.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0123',
    name: 'Talon',
    image: require('../assets/campeoes/talon.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0124',
    name: 'Taric',
    image: require('../assets/campeoes/taric.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0125',
    name: 'Teemo',
    image: require('../assets/campeoes/teemo.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0126',
    name: 'Thresh',
    image: require('../assets/campeoes/thresh.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0127',
    name: 'Tristana',
    image: require('../assets/campeoes/tristana.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0128',
    name: 'Trundle',
    image: require('../assets/campeoes/trundle.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0129',
    name: 'Tryndamere',
    image: require('../assets/campeoes/tryndamere.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0130',
    name: 'Twisted Fate',
    image: require('../assets/campeoes/tf.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0131',
    name: 'Twitch',
    image: require('../assets/campeoes/twitch.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0132',
    name: 'Udyr',
    image: require('../assets/campeoes/udyr.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0133',
    name: 'Urgot',
    image: require('../assets/campeoes/urgot.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0134',
    name: 'Varus',
    image: require('../assets/campeoes/varus.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0135',
    name: 'Vayne',
    image: require('../assets/campeoes/vayne.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0136',
    name: 'Veigar',
    image: require('../assets/campeoes/rumble.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0137',
    name: "Vel'Koz",
    image: require('../assets/campeoes/velkoz.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0138',
    name: 'Vex',
    image: require('../assets/campeoes/vex.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0139',
    name: 'Vi',
    image: require('../assets/campeoes/vi.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0140',
    name: 'Viego',
    image: require('../assets/campeoes/viego.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0141',
    name: 'Viktor',
    image: require('../assets/campeoes/viktor.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0142',
    name: 'Vladimir',
    image: require('../assets/campeoes/vladimir.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0143',
    name: 'Volibear',
    image: require('../assets/campeoes/volibear.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0144',
    name: 'Warwick',
    image: require('../assets/campeoes/warwick.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0145',
    name: 'Wukong',
    image: require('../assets/campeoes/wukong.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0146',
    name: 'Xayah',
    image: require('../assets/campeoes/xayah.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0147',
    name: 'Xerath',
    image: require('../assets/campeoes/xerath.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0148',
    name: 'Xin Zhao',
    image: require('../assets/campeoes/xinzhao.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0149',
    name: 'Yasuo',
    image: require('../assets/campeoes/yasuo.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0150',
    name: 'Yone',
    image: require('../assets/campeoes/yone.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0151',
    name: 'Yorick',
    image: require('../assets/campeoes/yorick.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0152',
    name: 'Yuumi',
    image: require('../assets/campeoes/yuumi.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0153',
    name: 'Zac',
    image: require('../assets/campeoes/zac.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0154',
    name: 'Zed',
    image: require('../assets/campeoes/zed.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0155',
    name: 'Zeri',
    image: require('../assets/campeoes/zeri.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0156',
    name: 'Ziggs',
    image: require('../assets/campeoes/ziggs.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0157',
    name: 'Zilean',
    image: require('../assets/campeoes/zilean.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0158',
    name: 'Zoe',
    image: require('../assets/campeoes/zoe.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
{
    key: '0159',
    name: 'Zyra',
    image: require('../assets/campeoes/zyra.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
},
];

export default champList;