const champList=[{
    key: '0000',
    name: 'Aatrox',
    image: require('../assets/campeoes/aatrox.png'),
    bordao: 'a Espada Darkin', 
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:["require('../assets/campeoes/jax.jpg')","require('../assets/campeoes/fiora.jpg')" ],
    fortecontra:'',
},
{
    key: '0001',
    name: 'Ahri',
    image: require('../assets/campeoes/ahri.png'),
    bordao: 'a Raposa de Nove Caudas',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0002',
    name: 'Akali',
    image: require('../assets/campeoes/akali.png'),
    bordao: 'o Punho das Sombras',
    rotas: 'Top e Mid',
    dano: 'Híbrido',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0003',
    name: 'Askhan',
    image: require('../assets/campeoes/askhan.jpg'),
    bordao: 'o Sentinela Rebelde',
    rotas: 'Top Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0004',
    name: 'Alistar',
    image: require('../assets/campeoes/alistar.jpg'),
    bordao: 'o Minotauro',
    rotas: 'Bot',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0005',
    name: 'Amumu',
    image: require('../assets/campeoes/amumu.jpg'),
    bordao: 'a Múmia Triste',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0006',
    name: 'Anivia',
    image: require('../assets/campeoes/anivia.jpg'),
    bordao: 'a Criofênix',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0007',
    name: 'Annie',
    image: require('../assets/campeoes/annie.jpg'),
    bordao: 'a Criança Sombria',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0008',
    name: 'Aphelios',
    image: require('../assets/campeoes/aphelios.jpg'),
    bordao: 'a Arma dos Devotos',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0009',
    name: 'Ashe',
    image: require('../assets/campeoes/ashe.jpg'),
    bordao: 'a Arqueira do Gelo',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0010',
    name: 'Aurelion Sol',
    image: require('../assets/campeoes/aurelion.jpg'),
    bordao: 'O Forjador de Estrelas',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0011',
    name: 'Azir',
    image: require('../assets/campeoes/azir.jpg'),
    bordao: 'o Imperador das Areias',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0012',
    name: 'Bardo',
    image: require('../assets/campeoes/bardo.jpg'),
    bordao: 'o Protetor Andarilho',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0013',
    name: "Bel'Veth",
    image: require('../assets/campeoes/belveth.jpg'),
    bordao: 'a Imperatriz do Vazio',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0014',
    name: 'Blitzcrank',
    image: require('../assets/campeoes/blitzcrank.jpg'),
    bordao: 'o Grande Golem a Vapor',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0015',
    name: 'Brand',
    image: require('../assets/campeoes/brand.jpg'),
    bordao: 'a Vingança Flamejante',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0016',
    name: 'Braum',
    image: require('../assets/campeoes/braum.jpg'),
    bordao: 'o Coração de Freljord',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0017',
    name: 'Caitlyn',
    image: require('../assets/campeoes/caitlyn.jpg'),
    bordao: 'a Xerife de Piltover',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0018',
    name: 'Camille',
    image: require('../assets/campeoes/camille.jpg'),
    bordao: 'laços Rasgados',
    rotas: 'Top',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0019',
    name: 'Cassiopeia',
    image: require('../assets/campeoes/cassiopeia.jpg'),
    bordao: 'o Abraço da Serpente',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0020',
    name: 'Cho Gath',
    image: require('../assets/campeoes/chogath.jpg'),
    bordao: 'o Terror do Vazio',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0021',
    name: 'Corki',
    image: require('../assets/campeoes/corki.jpg'),
    bordao: 'o Bombardeiro Ousado',
    rotas: 'Mid e Bot',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0022',
    name: 'Darius',
    image: require('../assets/campeoes/darius.jpg'),
    bordao: 'a Mão de Noxus',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0023',
    name: 'Diana',
    image: require('../assets/campeoes/diana.jpg'),
    bordao: 'o Escárnio da Lua',
    rotas: 'Top Jungle e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0024',
    name: 'Dr.Mundo',
    image: require('../assets/campeoes/drmundo.jpg'),
    bordao: 'o Louco de Zaun',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0025',
    name: 'Draven',
    image: require('../assets/campeoes/draven.jpg'),
    bordao: 'o Carrasco de Noxus',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0026',
    name: 'Ekko',
    image: require('../assets/campeoes/ekko.jpg'),
    bordao: 'o Rapaz que Estilhaçou o Tempo',
    rotas: 'Mid e Jungle',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0027',
    name: 'Elise',
    image: require('../assets/campeoes/elise.jpg'),
    bordao: 'a Rainha-Aranha',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0028',
    name: 'Evelynn',
    image: require('../assets/campeoes/evelynn.jpg'),
    bordao: 'a Criadora de Viúvas',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0029',
    name: 'Ezreal',
    image: require('../assets/campeoes/ezreal.jpg'),
    bordao: 'o Explorador Pródigo',
    rotas: 'Mid e Bot',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0030',
    name: 'Fiddlesticks',
    image: require('../assets/campeoes/fiddle.jpg'),
    bordao: 'o Mensageiro da Morte',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0031',
    name: 'Fiora',
    image: require('../assets/campeoes/fiora.jpg'),
    bordao: 'a Grande Duelista',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0032',
    name: 'Fizz',
    image: require('../assets/campeoes/fizz.jpg'),
    bordao: 'o Trapaceiro das Marés',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0033',
    name: 'Galio',
    image: require('../assets/campeoes/galio.jpg'),
    bordao: 'o Sentinela da Amargura',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0034',
    name: 'GangPlank',
    image: require('../assets/campeoes/gangplank.jpg'),
    bordao: 'o Terror dos Sete Mares',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0035',
    name: 'Garen',
    image: require('../assets/campeoes/garen.jpg'),
    bordao: 'o Poder de Demacia',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0036',
    name: 'Gnar',
    image: require('../assets/campeoes/gnar.jpg'),
    bordao: 'o Yordle Pré-Histórico',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0037',
    name: 'Gragas',
    image: require('../assets/campeoes/gragas.jpg'),
    bordao: 'o Badernista',
    rotas: 'Top Jungle e Mid',
    dano: 'Dano Mágico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0038',
    name: 'Graves',
    image: require('../assets/campeoes/graves.jpg'),
    bordao: 'o Foragido',
    rotas: 'Top Jungle e Mid',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0039',
    name: 'Gwen',
    image: require('../assets/campeoes/gwen.jpg'),
    bordao: 'a Costureira Encantada',
    rotas: 'Top',
    dano: 'Dano Mágico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0040',
    name: 'Hecarim',
    image: require('../assets/campeoes/hecarim.jpg'),
    bordao: 'a Sombra da Guerra',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0041',
    name: 'Heimerdinger',
    image: require('../assets/campeoes/heimerdinger.jpg'),
    bordao: 'o Inventor Idolatrado',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0042',
    name: 'Illaoi',
    image: require('../assets/campeoes/illaoi.jpg'),
    bordao: 'a Sacerdotisa Cráquem',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0043',
    name: 'Irelia',
    image: require('../assets/campeoes/irelia.jpg'),
    bordao: 'a Vontade das Lâminas',
    rotas: 'Top e Mid',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0044',
    name: 'Ivern',
    image: require('../assets/campeoes/ivern.jpg'),
    bordao: 'o Pai do Verde',
    rotas: 'Jungle e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0045',
    name: 'Janna',
    image: require('../assets/campeoes/janna.jpg'),
    bordao: 'a Fúria da Tormenta',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0046',
    name: 'Jarvan IV',
    image: require('../assets/campeoes/jarvan.jpg'),
    bordao: 'o Exemplo de Demacia',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0047',
    name: 'Jax',
    image: require('../assets/campeoes/jax.jpg'),
    bordao: 'o Grande Mestre das Armas',
    rotas: 'Top e Jungle',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0048',
    name: 'Jayce',
    image: require('../assets/campeoes/jayce.jpg'),
    bordao: 'o Defensor do Amanhã',
    rotas: 'Top e Mid',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0049',
    name: 'Jhin',
    image: require('../assets/campeoes/jhin.jpg'),
    bordao: 'o Virtuoso',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0050',
    name: 'Jinx',
    image: require('../assets/campeoes/jinx.jpg'),
    bordao: 'o Gatilho Desenfreado',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0051',
    name: "Kai'sa",
    image: require('../assets/campeoes/kaisa.jpg'),
    bordao: 'Filha do Vazio',
    rotas: 'Mid e ADC',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0052',
    name: 'Kalista',
    image: require('../assets/campeoes/kalista.jpg'),
    bordao: 'a Lança da Vingança',
    rotas: 'Top Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0053',
    name: 'Karma',
    image: require('../assets/campeoes/karma.jpg'),
    bordao: 'a Iluminada',
    rotas: 'Top Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0054',
    name: 'Karthus',
    image: require('../assets/campeoes/karthus.jpg'),
    bordao: 'a Voz Mortal',
    rotas: 'Top Mid Jungle e Bot/Atirador',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0055',
    name: 'Kassadin',
    image: require('../assets/campeoes/kassadin.jpg'),
    bordao: 'o Caçador do Vazio',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0056',
    name: 'Katarina',
    image: require('../assets/campeoes/katarina.jpg'),
    bordao: 'a Lâmina Sinistra',
    rotas: 'Top e Mid',
    dano: 'Híbrido',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0057',
    name: 'Kayle',
    image: require('../assets/campeoes/kayle.jpg'),
    bordao: 'a Julgadora',
    rotas: 'Top e Mid',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0058',
    name: 'Kayn',
    image: require('../assets/campeoes/kayn.jpg'),
    bordao: 'o Ceifador de Sombras',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador/Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0059',
    name: 'Kennen',
    image: require('../assets/campeoes/kennen.jpg'),
    bordao: 'o Coração da Tempestade',
    rotas: 'Top',
    dano: 'Híbrido',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0060',
    name: "Kha'Zix",
    image: require('../assets/campeoes/khazix.jpg'),
    bordao: 'o Ceifador do Vazio',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0061',
    name: 'Kindred',
    image: require('../assets/campeoes/kindred.jpg'),
    bordao: 'os Caçadores Eternos',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0062',
    name: 'Kled',
    image: require('../assets/campeoes/kled.jpg'),
    bordao: 'o Cavaleiro Furioso',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0063',
    name: "Kog'Maw",
    image: require('../assets/campeoes/kogmaw.jpg'),
    bordao: 'a Boca do Abismo',
    rotas: 'Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0064',
    name: 'Leblanc',
    image: require('../assets/campeoes/leblanc.jpg'),
    bordao: 'a Falsa',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0065',
    name: 'Lee Sin',
    image: require('../assets/campeoes/leesin.jpg'),
    bordao: 'o Monge Cego',
    rotas: 'Top Mid e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0066',
    name: 'Leona',
    image: require('../assets/campeoes/leona.jpg'),
    bordao: 'a Alvorada Radiante',
    rotas: 'Bot/Suporte',
    dano: 'Dano Físico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0067',
    name: 'Lilia',
    image: require('../assets/campeoes/lilia.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0068',
    name: 'Lissandra',
    image: require('../assets/campeoes/lissandra.jpg'),
    bordao: 'o Florir Receoso',
    rotas: 'Top e Jungle',
    dano: 'Dano Mágico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0069',
    name: 'Lucian',
    image: require('../assets/campeoes/lucian.jpg'),
    bordao: 'o Purificador',
    rotas: 'Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0070',
    name: 'Lulu',
    image: require('../assets/campeoes/lulu.jpg'),
    bordao: 'a Fada Feiticeira',
    rotas: 'Top Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0071',
    name: 'Lux',
    image: require('../assets/campeoes/lux.jpg'),
    bordao: 'a Dama da Luz',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0072',
    name: 'Malphite',
    image: require('../assets/campeoes/malphite.jpg'),
    bordao: 'o Fragmento do Monolito',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0073',
    name: 'Malzahar',
    image: require('../assets/campeoes/malzahar.jpg'),
    bordao: '',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0074',
    name: 'Maokai',
    image: require('../assets/campeoes/maokai.jpg'),
    bordao: 'o Profeta do Vazio',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0075',
    name: 'Master Yi',
    image: require('../assets/campeoes/masteryi.jpg'),
    bordao: 'o Espadachim Wuju',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador/Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0076',
    name: 'Miss Fortune',
    image: require('../assets/campeoes/missfortune.jpg'),
    bordao: 'a Caçadora de Recompensas',
    rotas: 'Mid e Bot',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0077',
    name: 'Mordekaizer',
    image: require('../assets/campeoes/mordekaizer.jpg'),
    bordao: 'o Mestre do Metal',
    rotas: 'Top Mid e Jungle',
    dano: 'Dano Mágico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0078',
    name: 'Morgana',
    image: require('../assets/campeoes/morgana.jpg'),
    bordao: 'o Anjo Caído',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0079',
    name: 'Nami',
    image: require('../assets/campeoes/nami.jpg'),
    bordao: 'a Conjuradora das Marés',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0080',
    name: 'Nasus',
    image: require('../assets/campeoes/nasus.jpg'),
    bordao: 'o Curador das Areias',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0081',
    name: 'Nautilus',
    image: require('../assets/campeoes/nautilus.jpg'),
    bordao: 'o Titã das Profundezas',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0082',
    name: 'Neeko',
    image: require('../assets/campeoes/neeko.jpg'),
    bordao: 'a Camaleoa Curiosa',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0083',
    name: 'Nidalee',
    image: require('../assets/campeoes/nidalee.jpg'),
    bordao: 'a Caçadora Bestial',
    rotas: 'Jungle',
    dano: 'Híbrido',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0084',
    name: 'Nocturne',
    image: require('../assets/campeoes/nocturne.jpg'),
    bordao: 'o Eterno Pesadelo',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0085',
    name: 'Nunu',
    image: require('../assets/campeoes/nunu.jpg'),
    bordao: 'o Domador de Yetis',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0086',
    name: 'Olaf',
    image: require('../assets/campeoes/olaf.jpg'),
    bordao: 'o Berserker',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0087',
    name: 'Orianna',
    image: require('../assets/campeoes/orianna.jpg'),
    bordao: 'a Donzela Mecânica',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0088',
    name: 'Ornn',
    image: require('../assets/campeoes/ornn.jpg'),
    bordao: 'o Fogo sob a Montanha',
    rotas: 'Top',
    dano: 'Híbrido',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0089',
    name: 'Pantheon',
    image: require('../assets/campeoes/pantheon.jpg'),
    bordao: 'o Artesão da Guerra',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0090',
    name: 'Poppy',
    image: require('../assets/campeoes/poppy.jpg'),
    bordao: 'a Embaixadora Ferreira',
    rotas: 'Top Jungle',
    dano: 'Híbrido',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0091',
    name: 'Pyke',
    image: require('../assets/campeoes/pyke.jpg'),
    bordao: 'o Estripador das Águas Sangrentas',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0092',
    name: 'Qiyana',
    image: require('../assets/campeoes/qiyana.jpg'),
    bordao: 'a Imperatriz dos Elementos',
    rotas: 'Mid e Jungle',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0093',
    name: 'Quinn',
    image: require('../assets/campeoes/quinn.jpg'),
    bordao: 'as Asas de Demacia',
    rotas: 'Top e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0094',
    name: 'Rakan',
    image: require('../assets/campeoes/rakan.jpg'),
    bordao: 'o Encantador',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0095',
    name: 'Rammus',
    image: require('../assets/campeoes/rammus.jpg'),
    bordao: 'o Tatu Blindado',
    rotas: 'Jungle',
    dano: 'Híbrido',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0096',
    name: "Rek'Sai",
    image: require('../assets/campeoes/reksai.jpg'),
    bordao: 'a Escavadora do Vazio',
    rotas: 'Top Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0097',
    name: 'Rell',
    image: require('../assets/campeoes/rell.jpg'),
    bordao: 'a Dama de Ferro',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0098',
    name: 'Renata Glasc',
    image: require('../assets/campeoes/renata.jpg'),
    bordao: 'a Baronesa Da Química',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0099',
    name: 'Renekton',
    image: require('../assets/campeoes/renekton.jpg'),
    bordao: 'o Carniceiro das Areias',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0100',
    name: 'Rengar',
    image: require('../assets/campeoes/rengar.jpg'),
    bordao: 'o Acossador da Alcateia',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador/Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0101',
    name: 'Riven',
    image: require('../assets/campeoes/riven.jpg'),
    bordao: 'a Exilada',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0102',
    name: 'Rumble',
    image: require('../assets/campeoes/rumble.jpg'),
    bordao: 'a Ameaça Mecânica',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0103',
    name: 'Ryze',
    image: require('../assets/campeoes/ryze.jpg'),
    bordao: 'o Mago Rúnico',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0104',
    name: 'Samira',
    image: require('../assets/campeoes/samira.jpg'),
    bordao: 'a Rosa Do Deserto',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0105',
    name: 'Sejuani',
    image: require('../assets/campeoes/sejuani.jpg'),
    bordao: 'a Fúria Do Norte',
    rotas: 'Jungle',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0106',
    name: 'Senna',
    image: require('../assets/campeoes/senna.jpg'),
    bordao: 'a Redentora',
    rotas: 'Bot/Atirador e Suporte',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0107',
    name: 'Seraphine',
    image: require('../assets/campeoes/seraphine.jpg'),
    bordao: 'a Cantora Sonhadora',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0108',
    name: 'Sett',
    image: require('../assets/campeoes/sett.jpg'),
    bordao: 'o Chefe',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0109',
    name: 'Shaco',
    image: require('../assets/campeoes/shaco.jpg'),
    bordao: 'o Bufão Demoníaco',
    rotas: 'Jungle',
    dano: 'Híbrido',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0110',
    name: 'Shen',
    image: require('../assets/campeoes/shen.jpg'),
    bordao: 'o Olho Do Crepúsculo',
    rotas: 'Top e Bot/Suporte',
    dano: 'Dano Físico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0111',
    name: 'Shyvana',
    image: require('../assets/campeoes/shyvana.jpg'),
    bordao: 'a Meio-Dragão',
    rotas: 'Top e Jungle',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0112',
    name: 'Singed',
    image: require('../assets/campeoes/singed.jpg'),
    bordao: 'o Químico Louco',
    rotas: 'Top',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0113',
    name: 'Sion',
    image: require('../assets/campeoes/sion.jpg'),
    bordao: 'o Colosso Morto-Vivo',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0114',
    name: 'Sivir',
    image: require('../assets/campeoes/sivir.jpg'),
    bordao: 'a Mestra Da Batalha',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0115',
    name: 'Skarner',
    image: require('../assets/campeoes/skarner.jpg'),
    bordao: 'a Vanguarda De Cristal',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0116',
    name: 'Sona',
    image: require('../assets/campeoes/sona.jpg'),
    bordao: 'a Mestra Das Cordas',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0117',
    name: 'Soraka',
    image: require('../assets/campeoes/soraka.jpg'),
    bordao: 'a Filha Das Estrelas',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0118',
    name: 'Swain',
    image: require('../assets/campeoes/swain.jpg'),
    bordao: 'o Grande General Noxiano',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0119',
    name: 'Sylas',
    image: require('../assets/campeoes/sylas.jpg'),
    bordao: 'o Abjugado',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0120',
    name: 'Syndra',
    image: require('../assets/campeoes/syndra.jpg'),
    bordao: 'a Soberana Sombria',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0121',
    name: 'Tahm Kench',
    image: require('../assets/campeoes/tk.jpg'),
    bordao: 'o Rei Do Rio',
    rotas: 'Top',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0122',
    name: 'Taliyah',
    image: require('../assets/campeoes/taliyah.jpg'),
    bordao: 'a Tecelã De Pedras',
    rotas: 'Mid e Jungle',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0123',
    name: 'Talon',
    image: require('../assets/campeoes/talon.jpg'),
    bordao: 'a Sombra Da Lâmina',
    rotas: 'Mid e jungle',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0124',
    name: 'Taric',
    image: require('../assets/campeoes/taric.jpg'),
    bordao: 'o Escudo De Valoran',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0125',
    name: 'Teemo',
    image: require('../assets/campeoes/teemo.jpg'),
    bordao: 'o Explorador Veloz',
    rotas: 'Top',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0126',
    name: 'Thresh',
    image: require('../assets/campeoes/thresh.jpg'),
    bordao: 'o Guardião Das Correntes',
    rotas: 'Bot/Suporte',
    dano: 'Dano Físico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0127',
    name: 'Tristana',
    image: require('../assets/campeoes/tristana.jpg'),
    bordao: 'a Artilheira Yordle',
    rotas: 'Mid e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0128',
    name: 'Trundle',
    image: require('../assets/campeoes/trundle.jpg'),
    bordao: 'o Rei Dos Trolls',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0129',
    name: 'Tryndamere',
    image: require('../assets/campeoes/tryndamere.jpg'),
    bordao: 'o Rei Bárbaro',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0130',
    name: 'Twisted Fate',
    image: require('../assets/campeoes/tf.jpg'),
    bordao: 'o Mestre Das Cartas',
    rotas: 'Mid',
    dano: 'Híbrido',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0131',
    name: 'Twitch',
    image: require('../assets/campeoes/twitch.jpg'),
    bordao: 'o Semeador Da Peste',
    rotas: 'Bot',
    dano: 'Híbrido',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0132',
    name: 'Udyr',
    image: require('../assets/campeoes/udyr.jpg'),
    bordao: 'o Andarilho Espiritual',
    rotas: 'Jungle',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0133',
    name: 'Urgot',
    image: require('../assets/campeoes/urgot.jpg'),
    bordao: 'o Encouraçado',
    rotas: 'Top',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0134',
    name: 'Varus',
    image: require('../assets/campeoes/varus.jpg'),
    bordao: 'a Flecha da Vingança',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0135',
    name: 'Vayne',
    image: require('../assets/campeoes/vayne.jpg'),
    bordao: 'a Caçadora Noturna',
    rotas: 'Top e Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0136',
    name: 'Veigar',
    image: require('../assets/campeoes/rumble.jpg'),
    bordao: 'o Pequeno Mestre Do Mal',
    rotas: 'Mid e Bot/Atirador',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0137',
    name: "Vel'Koz",
    image: require('../assets/campeoes/velkoz.jpg'),
    bordao: 'o Olho Do Vazio',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0138',
    name: 'Vex',
    image: require('../assets/campeoes/vex.jpg'),
    bordao: 'a Melancolista',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0139',
    name: 'Vi',
    image: require('../assets/campeoes/vi.jpg'),
    bordao: 'a Defensora De Piltover',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0140',
    name: 'Viego',
    image: require('../assets/campeoes/viego.jpg'),
    bordao: 'o Rei Destruído',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0141',
    name: 'Viktor',
    image: require('../assets/campeoes/viktor.jpg'),
    bordao: 'o Arauto Das Máquinas',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0142',
    name: 'Vladimir',
    image: require('../assets/campeoes/vladimir.jpg'),
    bordao: 'o Sanguinário Escarlate',
    rotas: 'Top e Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0143',
    name: 'Volibear',
    image: require('../assets/campeoes/volibear.jpg'),
    bordao: 'a Tempestade Implacável',
    rotas: 'Top e Jungle',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0144',
    name: 'Warwick',
    image: require('../assets/campeoes/warwick.jpg'),
    bordao: 'a Ira Dsimpedida De Zaun',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0145',
    name: 'Wukong',
    image: require('../assets/campeoes/wukong.jpg'),
    bordao: 'o Macaco Rei',
    rotas: 'Top e Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0146',
    name: 'Xayah',
    image: require('../assets/campeoes/xayah.jpg'),
    bordao: 'a Rebelde',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0147',
    name: 'Xerath',
    image: require('../assets/campeoes/xerath.jpg'),
    bordao: 'o Mago Ascendente',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0148',
    name: 'Xin Zhao',
    image: require('../assets/campeoes/xinzhao.jpg'),
    bordao: 'o Senescal De Demacia',
    rotas: 'Jungle',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0149',
    name: 'Yasuo',
    image: require('../assets/campeoes/yasuo.jpg'),
    bordao: 'o Imperdoável',
    rotas: 'Top e Mid',
    dano: 'Dano Físico',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0150',
    name: 'Yone',
    image: require('../assets/campeoes/yone.jpg'),
    bordao: 'o Inesquecido',
    rotas: 'Top e Mid',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0151',
    name: 'Yorick',
    image: require('../assets/campeoes/yorick.jpg'),
    bordao: 'o Pastor De Almas',
    rotas: 'Top',
    dano: 'Híbrido',
    funcao: 'Lutador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0152',
    name: 'Yuumi',
    image: require('../assets/campeoes/yuumi.jpg'),
    bordao: 'a Gata Mágica',
    rotas: 'Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0153',
    name: 'Zac',
    image: require('../assets/campeoes/zac.jpg'),
    bordao: 'a Arma Secreta',
    rotas: 'Top e Jungle',
    dano: 'Dano Mágico',
    funcao: 'Tank',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0154',
    name: 'Zed',
    image: require('../assets/campeoes/zed.jpg'),
    bordao: 'o Mestre Das Sombras',
    rotas: 'Mid',
    dano: 'Dano Físico',
    funcao: 'Assassino',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0155',
    name: 'Zeri',
    image: require('../assets/campeoes/zeri.jpg'),
    bordao: 'a Faísca De Zaun',
    rotas: 'Bot',
    dano: 'Dano Físico',
    funcao: 'Atirador',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0156',
    name: 'Ziggs',
    image: require('../assets/campeoes/ziggs.jpg'),
    bordao: 'o Especialista Em Hexplosivos',
    rotas: 'Mid e Bot/Atirador',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0157',
    name: 'Zilean',
    image: require('../assets/campeoes/zilean.jpg'),
    bordao: 'o Guardião Do Tempo',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Suporte',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0158',
    name: 'Zoe',
    image: require('../assets/campeoes/zoe.jpg'),
    bordao: 'o Aspecto Do Crepúsculo',
    rotas: 'Mid',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
{
    key: '0159',
    name: 'Zyra',
    image: require('../assets/campeoes/zyra.jpg'),
    bordao: 'a Ascensão Dos Espinhos',
    rotas: 'Mid e Bot/Suporte',
    dano: 'Dano Mágico',
    funcao: 'Mago',
    fracocontra:'',
    fortecontra:'',
},
];

export default champList;